services:
  mysql:
    image: 'mysql:latest'
    volumes:
      - /Users/ankitkumar/Downloads/demo:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
